# Write your MySQL query statement below
SELECT CUSTOMERS.NAME AS CUSTOMERS 
FROM CUSTOMERS 
WHERE ID NOT IN
(
    SELECT CUSTOMERS.ID FROM CUSTOMERS
    INNER JOIN ORDERS 
    ON CUSTOMERS.ID = ORDERS.CUSTOMERID
) 
